version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: eventapp-frontend
    ports:
      - "8080:80"       # frontend accessible at localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html   # live reload for frontend files

  backend:
    build: ./backend
    
    ports:
      - "8001:8000"    # backend accessible at localhost:8000
    volumes:
      - ./backend:/app  # live reload for Django code + SQLite file
    environment:
      - DEBUG=True      # optional: enable Django debug mode
